### ISSUE TITLE
Details on breaking change for 12.0.0

### ISSUE THREAD

**Issue by thomasleese** [HMPO/hmpo-form-wizard#174]
I'm looking to upgrade this dependency in one of our projects (https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/2271) and I'm trying to find what the breaking change was for the bump from version 11 to 12, but I can't seem to find it documented anywhere.

I was wondering if it was related to the minimum Node version change in https://github.com/HMPO/hmpo-form-wizard/commit/0c446958f8f0e4f5b8d34ee353c7a568e5a32f46 but I couldn't be sure.

**Comment by HughePaul** [comment]
Hi,

The main change was using Object.create(null) which creates prototype-less objects for storage of internal dictionaries with less possibility of prototype pollution vulnerabilities.

So, in addition to the minimum node version to mainly support updates to the test libraries, the breaking change was "check that things still work as you expect" rather than having to change anything in particular.

**Comment by thomasleese** [comment]
Okay, thanks, that's helpful.
